### ISSUE TITLE
Website blocked in India

### ISSUE THREAD

**Issue by captn3m0** [pennapps/pennapps.com-legacy#18]
What: pennapps.com is blocked in India

Why: https://github.com/captn3m0/hello-cloudflare

How to Fix: https://github.com/captn3m0/hello-cloudflare#help-my-website-is-blocked

First reported here: https://github.com/captn3m0/hello-cloudflare/pull/3

**Comment by audrey-yang** [comment]
Hi @captn3m0, this repository is not for garudahacks.com. Is this also an issue with pennapps.com?

**Comment by captn3m0** [comment]
Was creating these issues in bulk yesterday, and I put it incorrectly. 

Edited now~~Will edit in a bit~~, but yeah - it's an issue for penapps.com.
